[project]
name = "chatgpt-proxy"
version = "0.1.0"
description = "ChatGPT proxy server for UnrealScript / UE3 bots."
readme = "README.md"
requires-python = ">=3.13"
license-files = ["LICENSE"]
dependencies = [
    "asyncpg>=0.30.0",
    "loguru>=0.7.3",
    "openai>=1.88.0",
    "sanic[ext]>=25.3.0",
]

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "ruff>=0.12.0",
]
