name: Python package builds and tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]

    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/chatgpt_proxy_tests

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up container
        run: |
          apt update
          apt install -y --no-install-recommends \
            ca-certificates \
            git \
            jq

      - uses: actions/checkout@v4

      - name: Mark workspace as safe for git
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory ${{ github.workspace }}/*
          git config --global --add safe.directory ${{ github.workspace }}/**
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: ./chatgpt_proxy/uv.lock

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        working-directory: ./chatgpt_proxy
        run: |
          uv sync --locked --all-extras --dev

      - name: Build project
        working-directory: ./chatgpt_proxy
        run: |
          uv build

      - name: Run mypy
        working-directory: ./chatgpt_proxy
        continue-on-error: true
        run: |
          uv run mypy . --output=json | jq -r '"::error title=Mypy issue,file=\(.file),line=\(.line),col=\(.column)::\(.message)"'

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        continue-on-error: true
        with:
          src: ./chatgpt_proxy

      - name: Run pytest
        working-directory: ./chatgpt_proxy
        run: |
          uv run pytest

      - name: Minimize uv cache
        working-directory: ./chatgpt_proxy
        run: uv cache prune --ci
